# -*- coding: utf-8 -*-
"""Rock,Paper and Scissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/188qrramT1Fx_qGtrwuKuwg8139lwimso
"""

import random
def check():
  player=input("Enter a choice:{Rock,Paper,Scissors}")
  computerchoices=["Rock", "Paper", "Scissors"]
  computer=random.choice(computerchoices)
  print("Player:"+" "+player+" "+"Computer:"+" "+computer)
  if player not in computerchoices:
    return "Enter a Valid Input"
  if player==computer:
    return "It is a tie"
  else:
    if (player=="Rock" and computer=="Scissors") or \
    (player=="Scissors" and computer=="Paper") or \
    (player=="Paper" and computer=="Rock"):
      return "Player wins"
    else:
      return "Computer wins"
print(check())